version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
    # Collect all updates in a single PR
    groups:
      github-actions:
        patterns:
          - "*"
